[build.environment]
	NODE_VERSION = "16"
	NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  publish = ".vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npx pnpm build"

[dev]
	command = "pnpm run dev"
	targetPort = 3000
	autoLaunch = false
	framework = "#custom"
